FEATURE_ALGORITHMS = ["MI", "MS"]

RUN_PARALLEL = True
DATASET_PATH = "DemoData/"
EXPERIMENT_NAME = "demo"
OUTPUT_PATH = "OUTPUT/"

CLASS_LABEL = 'Class'
INSTANCE_LABEL = 'InstanceID'
RANDOM_STATE = 42

MODEL_ALGORITHMS = ["LR", "NB", "DT"]
EXCLUDE = ["XCS", "eLCS"]
