FEATURE_ALGORITHMS = ["MI", "MS"]

RUN_PARALLEL = True
DATASET_PATH = "./OSA/"
EXPERIMENT_NAME = "OSA"
OUTPUT_PATH = "./OSA_OUTPUT/"

CLASS_LABEL = 'class'
INSTANCE_LABEL = 'subnum'
RANDOM_STATE = 42

MODEL_ALGORITHMS = None
